///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LeaguesModel {
  String idLeague;
  String strLeague;
  String strSport;
  String strLeagueAlternate;

  LeaguesModel({
    this.idLeague,
    this.strLeague,
    this.strSport,
    this.strLeagueAlternate,
  });
  LeaguesModel.fromJson(Map<String, dynamic> json) {
    idLeague = json["idLeague"]?.toString();
    strLeague = json["strLeague"]?.toString();
    strSport = json["strSport"]?.toString();
    strLeagueAlternate = json["strLeagueAlternate"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["idLeague"] = idLeague;
    data["strLeague"] = strLeague;
    data["strSport"] = strSport;
    data["strLeagueAlternate"] = strLeagueAlternate;
    return data;
  }
}
